stages:
  data_preprocess:
    cmd: python src/data/data_preprocess.py
    deps:
    - src/data/data_preprocess.py
    params:
    - data_preprocess.random_state
    - data_preprocess.test_size
    outs:
    - data/raw
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/make_dataset.py
    outs:
    - data/processed
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed/test_processed.csv
    - data/processed/train_processed.csv
    - src/features/build_features.py
    params:
    - build_features.max_features
    outs:
    - data/feature
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/feature/train_bow.csv
    - src/models/model_building.py
    params:
    - model_building.C
    - model_building.solver
    - model_building.penalty
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python -m src.models.model_evaluation
    deps:
    - data/feature/test_bow.csv
    - models/model.pkl
    - src/models/model_evaluation.py
    outs:
    - reports/confusion_matrix.npy
    metrics:
    - metrics.json
