data_preprocess:
  test_size : 0.4
  random_state: 30

build_features:
  max_features: 1000

model_building:
  C: 1
  solver: liblinear
  penalty: l2

model_evaluation:
  model_path : models/model.pkl
  test_data_path: data/feature/test_bow.csv
  metrics_path: metrics.json